### ISSUE TITLE
hi, how can I easily use it in my training procedure?

### ISSUE THREAD

**Issue by Ritian-Li** [hiyouga/AMP-Regularizer#2]

**Comment by hiyouga** [comment]
Of course! Please feel free to use our code in your own project, and we will appreciate you if you kindly refer to our work.

**Comment by hiyouga** [comment]
A nice problem, we are making efforts to provide a simple PyTorch optimizer that you can plug into your program easily. We will update it soon and notify you timely.

**Comment by Ritian-Li** [comment]
Thank you for your nice work and waiting for good news!

**Comment by hiyouga** [comment]
I have implemented AMP as a regular optimizer and updated the code, please check the updated [README](Inner iteration number) file for easily using AMP in your training procedure.

**Comment by hiyouga** [comment]
I have implemented AMP as a regular optimizer and updated the code, please check the updated [README](https://github.com/hiyouga/AMP-Regularizer#usage) file for easily using AMP in your training procedure.

**Comment by Ritian-Li** [comment]
Thank you for your notice and for everything you and your team have done!
